import re
import pickle
from pydantic import BaseModel
from typing import List, Optional
from src.indexer import BM25Index
from src.models.utils import TerminalColors
from src.models.minimalSource import MinimalSource


class CodebaseRetriever(BaseModel):
    """
    Retriever that loads a pre-computed BM25 index and scores queries
    against it.

    This class handles the deserialization of the binary index and applies the
    Okapi BM25 ranking function to find the most relevant chunks of code or
    documentation for a given natural language query.

    Attributes:
        k1 (float): The term frequency saturation parameter. Controls how
            quickly the score plateaus as a term appears more frequently
            in a chunk.
        b (float): The document length normalization parameter. Controls the
            penalty applied to longer chunks compared to the average chunk
            length.
        index (Optional[BM25Index]): The loaded index containing the corpus
            statistics. Remains None until `load_index()` is explicitly called.
    """
    k1: float = 1.5
    b: float = 0.75
    index: Optional[BM25Index] = None

    def load_index(self, index_path: str) -> None:
        """
        Load the serialized BM25 index from disk into memory.

        Reads the binary pickle file generated by the `CodebaseIndexer` and
        reconstructs the `BM25Index` Pydantic model.

        Args:
            index_path (str): The file path to the saved binary index.

        Raises:
            RuntimeError: If the file is missing, unreadable, or if the binary
                data is corrupted/invalid.
        """
        try:
            with open(index_path, "rb") as f:
                data = pickle.load(f)
                self.index = BM25Index(**data)
            TerminalColors.success(
                f"Index successfully loaded from {index_path}"
            )
        except (
                FileNotFoundError,
                EOFError,
                pickle.UnpicklingError) as e:
            raise RuntimeError(
                f"File '{index_path}' not found or corrupted."
            ) from e

    def search(self, query: str, k: int) -> List[MinimalSource]:
        """
        Score all indexed chunks against the query and return the top-k
        sources.

        Tokenizes the input query, iterates over all indexed documents, and
        calculates their Okapi BM25 score using the pre-computed IDF and TF
        values. The results are sorted in descending order of relevance.

        Args:
            query (str): The raw text query to search for.
            k (int): The maximum number of top-scoring sources to return.

        Returns:
            List[MinimalSource]: A list of the most relevant sources, formatted
                with their file paths and exact character boundaries. Returns
                an empty list if the query is empty or `k` is invalid.

        Raises:
            ValueError: If called before the index has been successfully
                loaded.
        """
        if not query or not query.strip():
            TerminalColors.warning(
                "Empty query received. Returning no sources."
            )
            return []
        if k <= 0:
            TerminalColors.warning(
                f"Requested k={k} is invalid. Returning no sources."
            )
            return []
        if self.index is None:
            raise ValueError(
                "Index is not loaded. Please call load_index() first."
            )

        query_tokens = re.findall(r'\w+', query.lower())

        scores = []

        for i, chunk_tf in enumerate(self.index.doc_term_freqs):
            score = 0.0
            doc_len = self.index.doc_lengths[i]

            for token in query_tokens:
                if token not in self.index.df:
                    continue

                tf = chunk_tf.get(token, 0)
                if tf == 0:
                    continue

                idf = self.index.idf[token]
                numerator = tf * (self.k1 + 1)
                doc_base = doc_len / self.index.avg_doc_len
                doc_factor = 1 - self.b + self.b * doc_base
                denominator = tf + self.k1 * doc_factor

                score += idf * (numerator / denominator)

            scores.append((score, i))

        scores.sort(key=lambda x: x[0], reverse=True)

        top_sources = []
        for score, idx in scores[:k]:
            chunk = self.index.chunks[idx]
            top_sources.append(
                MinimalSource(
                    file_path=chunk.file_path,
                    first_character_index=chunk.first_character_index,
                    last_character_index=chunk.last_character_index
                )
            )

        return top_sources
